[project]
name = "gateway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "databricks-zerobus",
]

[tool.uv.sources]
databricks-zerobus = { path = "vendor/databricks_zerobus-0.0.15-py3-none-any.whl" }
